AllCops:
  Exclude:
    - "Gemfile"
    - "Gemfile.lock"
    - "config/create_markdown_schema_settings/db_schema.rb"
    - "config/create_test_settings/set_application_settings.rb"

  TargetRubyVersion: 3.0.6

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Style/Documentation:
  Enabled: false
