permissions:
  admin:
    dashboards: [read]
    customer_control_panels: [read, write]
    customers: [read, write, delete]
    places: [read, write, delete, submit, approve]
    incidents: [read, write, delete, import]
    incident_check_items: [read, write, delete]
    incident_check_lists: [read, write, delete]
    broadcast_request_check_lists: [read, write, delete]
    incident_status_logs: [read, write, delete]
    broadcast_request_status_logs: [read, write, delete]
    estimates: [read, write, delete]
    signages: [read, write, delete, import]
    broadcast_methods: [read, write, delete]
    broadcast_requests: [read, write, delete]
    channels: [read, write, delete]
    screen_structures: [read, write, delete]
    operation_groups: [read, write, delete]
    plots: [read, write, delete]
    systems: [read, write, delete]
    place_files: [read, write, delete]
    partners: [read, write, delete]
    supports: [read, write, delete]
    watchings: [read]
    watching_devices: [read, write, delete]
    agreements: [read, write, delete]
    agreement_periods: [read]
    users: [read, write, delete, import]
    passwords: [write]
    inquiries: [read, write, delete]
    questions: [read, write, delete]
    notices: [read, write, delete]
    manuals: [read, write, delete]
    error_logs: [write]
    alert_emails: [read, write, delete]
    place_file_tabs: [read, write, delete]
    applications: [read, write, delete]
    devices: [read, write, delete]
    makers: [read, write, delete]
    signage_devices: [read, write, delete]
  operator:
    dashboards: [read]
    customer_control_panels: [read, write]
    customers: [read]
    partners: [read]
    supports: [read]
    agreement_periods: [read]
    agreements: [read]
    places: [read]
    signages: [read]
    plots: [read]
    systems: [read]
    place_files: [read]
    broadcast_methods: [read]
    channels: [read]
    operation_groups: [read]
    screen_structures: [read]
    incidents: [read]
    incident_check_items: []
    incident_check_lists: []
    incident_status_logs: [read, write]
    inquiries: [read, write]
    estimates: []
    users: []
    passwords: [write]
    notices: []
    questions: [read]
    manuals: [read]
    broadcast_requests: [read, write, delete, import]
    broadcast_request_check_lists: [read, write]
    broadcast_request_status_logs: [read, write]
    place_file_tabs: []
    applications: []
    devices: []
    makers: []
    signage_devices: []
  broadcast_admin:
    dashboards: [read]
    customer_control_panels: [read, write]
    customers: [read]
    partners: [read]
    supports: [read]
    agreement_periods: [read]
    agreements: [read]
    places: [read]
    signages: [read, write, delete, import]
    plots: [read]
    systems: [read, write, delete]
    place_files: [read, write, delete]
    broadcast_methods: [read, write, delete]
    channels: [read, write, delete]
    operation_groups: [read, write, delete]
    screen_structures: [read, write, delete]
    incidents: [read]
    incident_check_items: [read, write, delete]
    incident_check_lists: []
    incident_status_logs: [read, write]
    inquiries: [read, write]
    estimates: []
    users: [limit_write, limit_read, limit_delete]
    passwords: [write]
    notices: []
    questions: [read]
    manuals: [read]
    broadcast_requests: [read, write, delete, import]
    broadcast_request_check_lists: [read, write, delete]
    broadcast_request_status_logs: [read, write, delete]
    place_file_tabs: []
    applications: []
    devices: []
    makers: []
    signage_devices: []
  maintenance:
    dashboards: [read]
    customer_control_panels: [read, write]
    customers: [read, write, delete]
    places: [read, write, submit, approve]
    incidents: [read, write, import]
    incident_check_items: [read, write, delete]
    incident_check_lists: [read, write, delete]
    broadcast_request_check_lists: []
    incident_status_logs: [read, write, delete]
    broadcast_request_status_logs: [read, write, delete]
    estimates: [read, write, delete]
    signages: [read, write, delete, import]
    broadcast_methods: [read, write, delete]
    broadcast_requests: [read, write, delete, import]
    channels: [read, write, delete]
    screen_structures: [read, write, delete]
    operation_groups: [read, write, delete]
    plots: [read, write, delete]
    systems: [read, write, delete]
    place_files: [read, write, delete]
    partners: [read, write, delete]
    supports: [read, write, delete]
    agreements: [read, write, delete]
    agreement_periods: [read]
    users: [read, write, delete]
    passwords: [write]
    inquiries: []
    questions: [read, write, delete]
    notices: [read, write, delete]
    manuals: [read, write, delete]
    error_logs: [write]
    alert_emails: []
    place_file_tabs: []
    applications: [read, write, delete]
    devices: [read, write, delete]
    makers: [read, write, delete]
    signage_devices: [read, write, delete]
  sales:
    dashboards: [read]
    customers: [read]
    places: [read, submit]
    incidents: [read]
    incident_check_items: []
    incident_check_lists: [read]
    broadcast_request_check_lists: [read]
    incident_status_logs: [read, write]
    broadcast_request_status_logs: [read, write]
    broadcast_methods: [read]
    broadcast_requests: [read]
    channels: [read]
    signages: []
    operation_groups: [read]
    screen_structures: [read]
    estimates: [read, write]
    plots: [read]
    systems: [read]
    place_files: [read]
    partners: [read]
    supports: [read]
    agreements: [read]
    agreement_periods: [read]
    users: []
    passwords: [write]
    inquiries: [read, write]
    questions: [read]
    notices: []
    manuals: [read]
    alert_emails: []
    place_file_tabs: []
    applications: []
    devices: []
    makers: []
    signage_devices: []
  se:
    dashboards: [read]
    customers: [read]
    places: [read, submit]
    incidents: [read]
    incident_check_items: []
    incident_check_lists: [read]
    broadcast_request_check_lists: [read]
    incident_status_logs: [read, write]
    broadcast_request_status_logs: [read, write]
    broadcast_requests: [read]
    broadcast_methods: [read, write, delete]
    channels: [read, write, delete]
    signages: []
    operation_groups: [read, write, delete]
    screen_structures: [read, write, delete]
    estimates: [read]
    plots: [read, write, delete]
    systems: [read, write, delete]
    place_files: [read, write, delete]
    partners: [read]
    supports: [read]
    agreements: [read]
    agreement_periods: [read]
    users: []
    passwords: [write]
    inquiries: [read, write]
    questions: [read]
    notices: []
    manuals: [read]
    alert_emails: []
    place_file_tabs: []
    applications: []
    devices: []
    makers: []
    signage_devices: []
  media:
    dashboards: [read]
    customers: [read]
    places: [read]
    incidents: [read]
    incident_check_items: []
    incident_check_lists: [read]
    broadcast_request_check_lists: [read, write, delete]
    incident_status_logs: [read, write]
    broadcast_request_status_logs: [read, write]
    broadcast_methods: [read]
    broadcast_requests: [read]
    channels: [read]
    operation_groups: [read]
    screen_structures: [read]
    estimates: [read]
    plots: [read]
    systems: [read]
    place_files: [read]
    partners: [read]
    supports: [read]
    agreements: [read]
    agreement_periods: [read]
    users: []
    passwords: [write]
    inquiries: [read, write]
    questions: [read]
    notices: []
    manuals: [read]
    alert_emails: []
    place_file_tabs: []
    applications: []
    devices: []
    makers: []
    signage_devices: []
  read_only:
    dashboards: [read]
    customers: [read]
    places: [read, submit]
    incidents: [read]
    incident_check_items: []
    incident_check_lists: [read]
    broadcast_request_check_lists: [read]
    incident_status_logs: [read]
    broadcast_request_status_logs: [read]
    estimates: [read]
    signages: [read]
    broadcast_methods: [read]
    broadcast_requests: [read]
    channels: [read]
    screen_structures: [read]
    operation_groups: [read]
    plots: [read]
    systems: [read]
    place_files: [read]
    partners: [read]
    supports: [read]
    agreements: [read]
    agreement_periods: [read]
    users: []
    passwords: [write]
    inquiries: []
    questions: [read]
    notices: []
    manuals: [read]
    place_file_tabs: []
    applications: []
    devices: []
    makers: []
    signage_devices: []
  call_center:
    dashboards: [read]
    customer_control_panels: [read, write]
    customers: [limit_read]
    places: [limit_read, submit]
    incidents: [read, write]
    incident_check_items: []
    incident_check_lists: [read, write]
    broadcast_request_check_lists: [read]
    incident_status_logs: [read, write]
    broadcast_request_status_logs: [read]
    estimates: []
    signages: [read]
    broadcast_methods: [read]
    broadcast_requests: [read]
    channels: [read]
    screen_structures: [read]
    operation_groups: [read]
    plots: [read]
    systems: [read]
    place_files: [read]
    partners: [read]
    supports: [read]
    agreements: []
    agreement_periods: []
    users: [read]
    passwords: [write]
    inquiries: []
    questions: [read]
    notices: []
    manuals: [read]
    error_logs: [write]
    alert_emails: []
    place_file_tabs: []
    applications: []
    devices: []
    makers: []
    signage_devices: []
  partner:
    dashboards: [read]
    customer_control_panels: [read, write]
    customers: [limit_read]
    places: [limit_read, submit]
    incidents: [read, write]
    incident_check_items: []
    incident_check_lists: [read, write]
    broadcast_request_check_lists: [read]
    incident_status_logs: [read, write]
    broadcast_request_status_logs: [read]
    estimates: []
    signages: [read]
    broadcast_methods: [read, write]
    broadcast_requests: [read]
    channels: [read, write]
    screen_structures: [read, write]
    operation_groups: [read, write]
    plots: [read, write]
    systems: [read, write]
    place_files: [read, write]
    partners: [read]
    supports: [read]
    agreements: []
    agreement_periods: []
    users: [read]
    passwords: [write]
    inquiries: []
    questions: []
    notices: []
    manuals: []
    error_logs: [write]
    alert_emails: []
    place_file_tabs: []
    applications: []
    devices: []
    makers: []
    signage_devices: []
  pdc_call_center:
    dashboards: [read]
    customer_control_panels: [read, write]
    customers: [read]
    places: [read, submit]
    incidents: [read, write]
    incident_check_items: []
    incident_check_lists: [read, write]
    broadcast_request_check_lists: [read]
    incident_status_logs: [read, write]
    broadcast_request_status_logs: [read]
    estimates: []
    signages: [read]
    broadcast_methods: [read]
    broadcast_requests: [read]
    channels: [read]
    screen_structures: [read]
    operation_groups: [read]
    plots: [read]
    systems: [read]
    place_files: [read]
    partners: [read]
    supports: [read]
    agreements: []
    agreement_periods: []
    users: [read]
    passwords: [write]
    inquiries: []
    questions: [read]
    notices: []
    manuals: [read]
    alert_emails: []
    place_file_tabs: []
    applications: []
    devices: []
    makers: []
    signage_devices: []
  customer:
    dashboards: [read]
    customers: []
    places: []
    incidents: []
    incident_check_items: []
    incident_check_lists: []
    broadcast_request_check_lists: []
    incident_status_logs: [read, write]
    broadcast_request_status_logs: [read, write]
    broadcast_requests: []
    broadcast_methods: []
    channels: []
    operation_groups: []
    screen_structures: []
    estimates: []
    signages: []
    plots: []
    systems: []
    place_files: []
    partners: []
    supports: []
    agreements: []
    agreement_periods: []
    users: []
    passwords: [write]
    email_and_names: [write]
    inquiries: [read, write]
    questions: [limit_read]
    notices: []
    manuals: [limit_read]
    error_logs: [write]
    alert_emails: []
    place_file_tabs: []
    applications: []
    devices: []
    makers: []
    signage_devices: []
